<script setup lang="ts">
const { can } = useAuth();
const allowed = computed(() => can('content.update.all') || can('settings.manage.all'));
const form = reactive<any>({ flat_fee: 0, free_shipping_threshold: null, shipping_enabled: true, pickup_enabled: true, pickup_instructions: '' });
const error = ref(''), saved = ref(false), busy = ref(false), loaded = ref(false), freeShipping = ref(false);
async function load() { if (!allowed.value) return; try { Object.assign(form, await api('/shipping-settings')); freeShipping.value = form.free_shipping_threshold !== null; loaded.value = true; } catch(e: any) { error.value = e.message; } }
async function save() { busy.value = true; error.value = ''; saved.value = false; try { Object.assign(form, await api('/shipping-settings', { method: 'PUT', body: { ...form, free_shipping_threshold: freeShipping.value ? form.free_shipping_threshold : null } })); saved.value = true; } catch(e: any) { error.value = e.message; } finally { busy.value = false; } }
onMounted(load);
</script>
<template><section v-if="allowed" class="card shipping-settings"><h2>配送與運費設定</h2><p class="muted">運費與免運門檻套用於整張訂單，金額以新臺幣計算。</p><p v-if="error" class="error" role="alert">{{ error }}</p><button v-if="!loaded" class="button ghost" @click="load">重新載入配送設定</button><form v-else @submit.prevent="save"><fieldset :disabled="busy"><div class="shipping-switches"><label><input v-model="form.shipping_enabled" type="checkbox" /> 開放宅配</label><label><input v-model="form.pickup_enabled" type="checkbox" /> 開放自取</label></div><div class="shipping-fields"><label class="field">宅配運費<input v-model.number="form.flat_fee" type="number" min="0" step="0.01" required /></label><div><label><input v-model="freeShipping" type="checkbox" @change="form.free_shipping_threshold ??= 0" /> 設定滿額免運</label><label v-if="freeShipping" class="field">免運商品小計門檻<input v-model.number="form.free_shipping_threshold" type="number" min="0" step="0.01" required /></label></div></div><label class="field">自取說明<textarea v-model="form.pickup_instructions" rows="2" maxlength="1000" placeholder="取貨地點、時間與聯絡方式" /></label><button class="button">{{ busy ? '儲存中…' : '儲存配送設定' }}</button><p v-if="saved" class="notice" role="status">配送設定已儲存。</p></fieldset></form></section></template>
<style scoped>.shipping-settings{margin-bottom:24px}.shipping-settings h2{margin-top:0}.shipping-settings fieldset{border:0;margin:0;padding:0;min-width:0}.shipping-switches{display:flex;gap:24px;flex-wrap:wrap;margin-bottom:18px}.shipping-fields{display:grid;grid-template-columns:1fr 1fr;gap:20px}.shipping-settings input[type=checkbox]{accent-color:var(--pine);width:18px;height:18px;vertical-align:middle}@media(max-width:600px){.shipping-fields{grid-template-columns:1fr;gap:0}}
</style>
